-- Создание таблицы карточек
CREATE TABLE card_table
(
    card_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    preview         TEXT,
    description     TEXT,
    link            TEXT,
    user_id         BIGINT,
    category        VARCHAR(255),
    price           BIGINT,
    platform        VARCHAR(255),
    recommendations TEXT,
    instructions    TEXT,
    CONSTRAINT fk_card_table_user_id FOREIGN KEY (user_id) REFERENCES user_table (user_id)
);

-- Создание таблицы тегов для карточек
CREATE TABLE card_tags
(
    card_id BIGINT,
    tag     VARCHAR(255),
    CONSTRAINT fk_card_tags_card_id FOREIGN KEY (card_id) REFERENCES card_table (card_id)
);
